steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/anee-cloudadption-proj/repo1/mypythonimage:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/anee-cloudadption-proj/repo1/mypythonimage:$SHORT_SHA']

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/repo1/mypythonimage:$SHORT_SHA'

options:
  logging: GCS_ONLY
  logsBucket: gs://buck2
